FROM debian:stretch

RUN export DEBIAN_FRONTEND=noninteractive; apt-get update \
	&& apt-get install --no-install-recommends -y gcj-jdk libgcj-common \
	&& apt-get autoremove -y \
	&& rm -rf /var/lib/apt/lists/*
