FROM ocaml/ocaml:debian-9

RUN export DEBIAN_FRONTEND=noninteractive; apt-get update \
	&& apt-get install --no-install-recommends -y libc-dev \
	&& apt-get autoremove -y \
	&& rm -rf /var/lib/apt/lists/*
